title: This Is The World
baseurl: ""
analytics_id: TO_SET
exclude: ['auto']
url: https://thisistheworld.net
analytics_id: UA-99830249-1
# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
