title: This Is The World
baseurl: ""
analytics_id: TO_SET
exclude: ['auto']
url: https://thisistheworld.net

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
