version: '2'

services:
  dev:
    build: .
    working_dir: /srv/jekyll
    command: ./run
    volumes:
      - .:/srv/jekyll
      - jekyll-apk-cache:/var/cache/apk/
      # - ruby2.4-gem-cache:/usr/local/bundle
    ports:
      - "4000:4000"
  prod:
    environment:
      - JEKYLL_ENV=production
    extends:
      service: dev

volumes:
  ruby2.4-gem-cache:
    external: true
  jekyll-apk-cache:
    external: true
